export const defaultImages = {
  business: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
  sports: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800&q=80",
  health: "https://images.unsplash.com/photo-1505751172107-573957a09d62?w=800&q=80",
  technology: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
  general: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&q=80",
  entertainment: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800&q=80",
  science: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&q=80",
  politics: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
  india: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
  defaultFallback: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&q=80",
};

export const defaultArticles = {
  business: [
    { title: "Wall Street Hits Record Highs Amid Economic Optimism", description: "Major indexes surged today as investors reacted to positive jobs data and easing inflation concerns.", urlToImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80", url: "https://www.reuters.com/business", source: "Reuters", author: "James Wilson" },
    { title: "Central Banks Signal Potential Rate Cuts in Q3", description: "Financial leaders suggest a shift in monetary policy as global price pressures begin to stabilize.", urlToImage: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800&q=80", url: "https://www.bloomberg.com/finance", source: "Bloomberg", author: "Sarah Chen" },
    { title: "Global Supply Chain Resilience Improves in Post-Pandemic Era", description: "Companies are diversifying manufacturing hubs to reduce dependency on single-source regions.", urlToImage: "https://images.unsplash.com/photo-1586528116311-ad8619665f80?w=800&q=80", url: "https://www.ft.com/logistics", source: "Financial Times", author: "Mark Evans" },
    { title: "Venture Capital Shifts Focus Toward Sustainable Tech Startups", description: "Investment trends indicate a strong preference for companies solving climate and energy challenges.", urlToImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80", url: "https://www.techcrunch.com/startups", source: "TechCrunch", author: "Alex Howard" },
    { title: "E-commerce Giants Expand Logistics for 1-Hour Delivery", description: "Major retailers are investing billions in local micro-fulfillment centers to win the speed race.", urlToImage: "https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?w=800&q=80", url: "https://www.wsj.com/retail", source: "WSJ Business", author: "Robert Smith" },
    { title: "The Rise of Neo-Banks: Reshaping Consumer Finance", description: "Digital-only banks are gaining massive market share by offering lower fees and superior apps.", urlToImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80", url: "https://www.forbes.com/fintech", source: "Forbes", author: "Emily Frost" },
    { title: "Energy Sector Transitions to Renewables Faster Than Expected", description: "Solar and wind infrastructure adoption is outpacing fossil fuel decommissioning globally.", urlToImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80", url: "https://www.cnbc.com/energy", source: "CNBC", author: "David Brooks" },
    { title: "Mergers & Acquisitions Hit Decade Low Amid High Interest Rates", description: "Corporate deal-making has slowed as borrowing costs remain elevated for major buyouts.", urlToImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80", url: "https://www.reuters.com/deals", source: "Reuters", author: "Liam O'Connor" },
    { title: "Luxury Goods Market Sees Cooling Demand in Key Asian Hubs", description: "High-end brands are adjusting forecasts as consumer spending in major cities begins to soften.", urlToImage: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80", url: "https://www.vogue.com/business", source: "Vogue Business", author: "Cathy Horyn" },
    { title: "Real Estate Commercial Sector Faces Challenges in Remote Era", description: "Office vacancy rates in major metropolis centers drive a rethink of urban development.", urlToImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80", url: "https://www.bloomberg.com/realestate", source: "Bloomberg News", author: "John Gittelsohn" }
  ],
  technology: [
    { title: "Quantum Milestone: Scalable Error Correction Achieved", description: "Researchers have demonstrated a logical qubit system that finally paves the way for practical quantum computers.", urlToImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80", url: "https://www.nature.com/technology", source: "Nature", author: "Dr. Alice Vance" },
    { title: "AI Models Move Toward Efficient Small Language Processing", description: "The industry is pivoting from massive 'black box' models to smaller, highly-efficient edge-based AI.", urlToImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80", url: "https://www.theverge.com/ai", source: "The Verge", author: "Nilay Patel" },
    { title: "Next-Gen Semiconductors Feature New Architecture for Heat Efficiency", description: "Chip designers are moving beyond x86 to specialized RISC-V designs for high-performance servers.", urlToImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80", url: "https://www.wired.com/hardware", source: "Wired", author: "Gideon Lewis-Kraus" },
    { title: "Data Privacy Standards Tighten Globally in New Tech Accord", description: "Major tech firms agree to a new framework for user data portability and enhanced encryption.", urlToImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80", url: "https://www.zdnet.com/security", source: "ZDNet", author: "Steven J. Vaughan-Nichols" },
    { title: "Foldable Smartphone Shipments Expected to Double This Year", description: "Improved hinge durability and lower price points are finally bringing foldables to the mainstream.", urlToImage: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&q=80", url: "https://www.engadget.com/mobile", source: "Engadget", author: "Cherlynn Low" },
    { title: "Cloud Gaming Infrastructure Reaches Maturity for Competitive Play", description: "Latency improvements allow for professional-level gaming on low-powered devices via the cloud.", urlToImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80", url: "https://www.polygon.com/tech", source: "Polygon", author: "Nicole Carpenter" },
    { title: "The Resurrection of VR: Mixed Reality Passes the Utility Test", description: "High-resolution passthrough is turning VR headsets from gaming toys into functional workspace tools.", urlToImage: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800&q=80", url: "https://www.cnet.com/reality", source: "CNET", author: "Scott Stein" },
    { title: "Battery Breakthrough: Graphene-Based Cells Charge in Seconds", description: "A new lab experiment has achieved energy density that could double electric vehicle range.", urlToImage: "https://images.unsplash.com/photo-1568410344099-7d4e09c50b78?w=800&q=80", url: "https://www.sciencedaily.com/tech", source: "ScienceDaily", author: "Ben Stephens" },
    { title: "Cybersecurity Shift: Zero-Trust Architecture Becomes Mandatory", description: "Government agencies are mandating strict verification protocols for all internal digital traffic.", urlToImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc4b?w=800&q=80", url: "https://www.darkreading.com", source: "Dark Reading", author: "Kelly Sheridan" },
    { title: "Web Expansion: Satellite Internet Reaches remote Rural Regions", description: "New low-earth orbit constellations are finally closing the digital divide for millions.", urlToImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80", url: "https://www.technewsworld.com", source: "TechNewsWorld", author: "Jack M. Germain" }
  ],
  sports: [
    { title: "Olympic Prep: Record-Breaking Sprint Times recorded in Trials", description: "Athletes are pushing the limits of human velocity with new training methodologies and gear.", urlToImage: "https://images.unsplash.com/photo-1502675135487-e971002a6adb?w=800&q=80", url: "https://www.espn.com/olympics", source: "ESPN Sport", author: "Michael Smith" },
    { title: "Underdog Leicester-Style Story developing in Major Football League", description: "A team with the lowest budget in the division is currently sitting at the top of the table.", urlToImage: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80", url: "https://www.bbc.com/football", source: "BBC Sport", author: "Gary Lineker" },
    { title: "Tennis World Awaits New No. 1 After Historic Season Finale", description: "The rankings are shifting as a new generation of players finally claims several major titles.", urlToImage: "https://images.unsplash.com/photo-1595435064212-36aa225791c6?w=800&q=80", url: "https://www.atptour.com", source: "ATP News", author: "James Buddell" },
    { title: "Formula 1: Urban Circuits Reshaping the Global Racing Calendar", description: "Night races in major city centers are drawing record viewership and younger audiences.", urlToImage: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&q=80", url: "https://www.autosport.com", source: "Autosport", author: "Jonathan Noble" },
    { title: "Basketball Global Evolution: European Talent Dominating the Draft", description: "The overseas scouting network is now producing more top-tier stars than the traditional systems.", urlToImage: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80", url: "https://www.nba.com/international", source: "NBA Global", author: "David Aldridge" },
    { title: "Cricket World Cup: Statistical Revolution in Short-Format Play", description: "Data analytics are changing the way captains set fields and batters choose their shots.", urlToImage: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80", url: "https://www.espncricinfo.com", source: "Cricinfo", author: "Sambit Bal" },
    { title: "E-sports Inclusion: Major Games recognized for International Multisport Events", description: "Digital competition is gaining official recognition from global governing bodies.", urlToImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80", url: "https://www.dexerto.com", source: "Dexerto", author: "Richard Lewis" },
    { title: "Golf's New Era: Technological Integration in Pro Circuit Gear", description: "AI-designed clubs and high-tech wearable monitors are providing players with minute edge data.", urlToImage: "https://images.unsplash.com/photo-1587174416062-a44599e57aeb?w=800&q=80", url: "https://www.pgatour.com", source: "PGA News", author: "Sean Martin" },
    { title: "Athletes for Climate: New Movement focused on Green Stadiums", description: "The biggest names in sport are pushing for zero-waste venues and sustainable travel.", urlToImage: "https://images.unsplash.com/photo-1551952237-954a0e68786c?w=800&q=80", url: "https://www.skysports.com", source: "Sky Sports", author: "Bryan Swanson" },
    { title: "Marathon Records fall as New Shoe Technology matures", description: "Sub-two-hour times are becoming a regular conversation as footwear engineering peaks.", urlToImage: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80", url: "https://www.runnersworld.com", source: "Runner's World", author: "Jeff Dengate" }
  ],
  science: [
    { title: "The Europa Mission: Proof of Hidden Ocean intensifies", description: "Planetary scientists have detected chemical signatures that strongly suggest salt-water currents on the moon.", urlToImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80", url: "https://www.nasa.gov", source: "NASA News", author: "Dr. Elena Rossi" },
    { title: "Nuclear Fusion Milestone: Sustained Reaction reaches New Duration", description: "A major laboratory has maintained solar-level plasma temperatures for several minutes, a key step for power.", urlToImage: "https://images.unsplash.com/photo-1532187863486-abf51ad9f69d?w=800&q=80", url: "https://www.nature.com/nature", source: "Nature Journal", author: "Alistair Brown" },
    { title: "Ancient Genomic Map Reveals intricate Human Migration Path", description: "Newly sequenced DNA from prehistoric sites is rewriting the timeline of when humans first arrived in remote regions.", urlToImage: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80", url: "https://www.science.org", source: "Science Org", author: "Robert Service" },
    { title: "Marine Ecosystem: Deep Sea species found with Unique Bioluminescence", description: "A deep-water drone has captured high-resolution video of a previously unknown light-emitting cephalopod.", urlToImage: "https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800&q=80", url: "https://www.nationalgeographic.com", source: "National Geographic", author: "Douglas Main" },
    { title: "Atmospheric Carbon Capture: High-Efficiency Catalyst developed", description: "Chemical engineers have created a porous material that can trap CO2 at 5x the efficiency of current systems.", urlToImage: "https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=800&q=80", url: "https://www.scientificamerican.com", source: "Scientific American", author: "Jeff Turrentine" },
    { title: "Neural Linkage: Mapping the entire Connectome of a Complex Organism", description: "For the first time, researchers have documented every single neuron and connection in a small vertebrate brain.", urlToImage: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80", url: "https://www.sciencedaily.com/neuro", source: "Science Daily", author: "Anna King" },
    { title: "Biodiversity Miracle: Species thought Extinct rediscovered in remote Jungle", description: "Conservationists on a remote island expedition found a small population of a bird last seen in 1912.", urlToImage: "https://images.unsplash.com/photo-1444464666168-49d633b867ad?w=800&q=80", url: "https://www.theguardian.com/science", source: "The Guardian", author: "Damian Carrington" },
    { title: "Quantum Entanglement: Distance record shattered for Secured Communication", description: "Physicists have successfully swapped quantum states over 1000km of fiber optic line.", urlToImage: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&q=80", url: "https://www.theconversation.com/science", source: "The Conversation", author: "Chris Anderson" },
    { title: "Sustainable Agriculture: Crops Engineered to Thrive in High-Salt Soil", description: "Genetic researchers have enabled rice and wheat variants to grow in coastal areas affected by rising sea levels.", urlToImage: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=800&q=80", url: "https://www.bbc.com/science", source: "BBC Science", author: "Victoria Gill" },
    { title: "Gravity Wave Astronomy: Detecting Pulsed signals from Black Hole Mergers", description: "New gravitational wave detectors provide a 'staccato' view of the most violent events in the galaxy.", urlToImage: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80", url: "https://www.skyandtelescope.org", source: "Sky & Telescope", author: "Monica Young" }
  ],
  health: [
    { title: "Mindfulness and the Heart: Clinical trials reveal direct biological links", description: "Long-term study shows patients with high meditation frequency have improved arterial elasticity.", urlToImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80", url: "https://www.mayoclinic.org/health", source: "Mayo Clinic", author: "Dr. John Doe" },
    { title: "The Next-Gen Vaccine platform: Universal flu shot begins human trials", description: "A highly-stable mRNA platform could protect against various strains with a single annual dose.", urlToImage: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&q=80", url: "https://www.who.int/health", source: "WHO", author: "Maria Garcia" },
    { title: "Personalized Nutrition: DNA Mapping for Optimized Dietary Plans", description: "How nutrient absorption rates vary drastically based on genetic markers, and what that means for your meals.", urlToImage: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80", url: "https://www.healthline.com", source: "Healthline", author: "Dr. Elizabeth Lane" },
    { title: "AI in Radiology: Breakthrough in Early Detection Accuracy", description: "Computer vision systems are now catching anomalies months before traditional human-led reviews.", urlToImage: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&q=80", url: "https://www.thelancet.com/health", source: "The Lancet", author: "James Gallagher" },
    { title: "Sleep Architecture: The link between deep REM and Alzheimer's Prevention", description: "Brain-cleansing 'glymphatic' cycles are only truly effective during specific stages of deep sleep.", urlToImage: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&q=80", url: "https://www.webmd.com", source: "WebMD", author: "Karia Johnson" },
    { title: "Metabolic Health: The role of Gut Microbes in Weight Management", description: "Fecal transplant studies provide shocking new data on how bacteria control our cravings and energy storage.", urlToImage: "https://images.unsplash.com/photo-1582560475093-ba66acc042d5?w=800&q=80", url: "https://www.medicalnewstoday.com", source: "MNT", author: "Yella Jones" },
    { title: "Telehealth Evolution: Remote surgery reaches rural outpost success", description: "A high-speed satellite link allowed a specialist in London to perform a procedure in a remote African clinic.", urlToImage: "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=800&q=80", url: "https://www.statnews.com", source: "STAT News", author: "Casey Ross" },
    { title: "The Aging Breakthrough: Senolytic drugs clear old cells in human subjects", description: "Preliminary trials show improved mobility and lung function in older patients after a targeted cell clearing regimen.", urlToImage: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&q=80", url: "https://www.sciam.com/health", source: "SciAm Health", author: "Tanya Lewis" },
    { title: "Modern Ergonomics: The link between standing desks and spinal longevity", description: "Physical therapists reveal why static standing is just as bad as sitting; movement is the key.", urlToImage: "https://images.unsplash.com/photo-1589149098258-3e9102ca93d3?w=800&q=80", url: "https://www.health.harvard.edu", source: "Harvard Health", author: "Dr. Robert Shmerling" },
    { title: "Pediatric Wellness: Screens and the developing brain's attention center", description: "New guidelines recommend strictly social-media-free windows for children under twelve.", urlToImage: "https://images.unsplash.com/photo-1584622781564-1d9876a13d00?w=800&q=80", url: "https://www.aap.org", source: "AAP News", author: "Jenna Jones" }
  ],
  entertainment: [
    { title: "Cinematic Epic: Director's cut of sci-fi masterpiece to feature 40 mins of extra footage", description: "Fans of high-concept visual effects under breathtaking landscapes are anticipating the global re-release.", urlToImage: "https://images.unsplash.com/photo-1485090916755-aa6cf5f144e7?w=800&q=80", url: "https://www.variety.com", source: "Variety", author: "Tim Gray" },
    { title: "Streaming wars update: Major platforms hit record cancellation rates", description: "As price increases hit, consumers are becoming more selective, rotating subscriptions based on specific show cycles.", urlToImage: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80", url: "https://www.hollywoodreporter.com", source: "Hollywood Reporter", author: "Borys Kit" },
    { title: "The Vinyl Revival: Collector market pushes sales to 1980s levels", description: "Limited edition pressings and high-fidelity mastering are making physical media a luxury status symbol.", urlToImage: "https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=800&q=80", url: "https://www.rollingstone.com", source: "Rolling Stone", author: "David Browne" },
    { title: "Immersive concerts: The VR headsets are finally good enough for live front-row seats", description: "New 12K 360-degree cameras are allowing fans to experience high-energy world tours from their living rooms.", urlToImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80", url: "https://www.billboard.com", source: "Billboard", author: "Katie Bain" },
    { title: "Indie Film Festival: Global breakout hits from underrepresented filmmakers", description: "This year's sleeper successes come from the vibrant creative HUBS of West Africa and Southeast Asia.", urlToImage: "https://images.unsplash.com/photo-1489599711129-00b54b2c8c0e?w=800&q=80", url: "https://www.indiewire.com", source: "IndieWire", author: "Eric Kohn" },
    { title: "Video Game Industry: Major shifts toward subscription-first models", description: "Large publishers are moving away from individual $70 releases in favor of consistent library access fees.", urlToImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80", url: "https://www.ign.com", source: "IGN", author: "Kat Bailey" },
    { title: "The Return of the Theatre: Broadway sees highest attendance in 5 years", description: "Classic revivals and experimental musicals are drawing diverse crowds back to the stage.", urlToImage: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&q=80", url: "https://www.playbill.com", source: "Playbill", author: "Logan Culwell-Block" },
    { title: "Podcast Giant: Exclusive network deal reaches 9-figure valuation", description: "The era of high-production, long-form conversational content continues its financial dominance.", urlToImage: "https://images.unsplash.com/photo-1590602847861-f357a93bb2be?w=800&q=80", url: "https://www.podnews.net", source: "Podnews", author: "James Cridland" },
    { title: "Fashion Week: Tech-integrated clothing takes center stage", description: "Smart fabrics that change opacity and temperature are no longer prototypes; they're on the runway.", urlToImage: "https://images.unsplash.com/photo-1537832816519-689ad163238b?w=800&q=80", url: "https://www.vogue.com", source: "Vogue", author: "Nicole Phelps" },
    { title: "Art Market: AI-generated physical sculpture auctions for millions", description: "Traditional collectors are finally recognizing the artistic merit of algorithmically derived physical forms.", urlToImage: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80", url: "https://www.artnews.com", source: "ArtNews", author: "Angelica Villa" }
  ],
  politics: [
    { title: "Global Climate Summit: Landmark agreement on carbon penalties", description: "World leaders signed a legally binding accord that mandates economic consequences for missed emission targets.", urlToImage: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80", url: "https://www.aljazeera.com", source: "Al Jazeera", author: "Ziad Ahmed" },
    { title: "Election Watch: Digital campaigning reaching unprecedented demographic targets", description: "The use of micro-targeting AI is becoming a central controversy in the upcoming national votes.", urlToImage: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&q=80", url: "https://www.theguardian.com", source: "The Guardian", author: "Marina Hyde" },
    { title: "Legislative Package: The New Digital Rights Bill explained", description: "A sweeping proposal aims to give citizens the legal 'Right to Forget' across all major internet services.", urlToImage: "https://images.unsplash.com/photo-1555848962-6ebd0797989d?w=800&q=80", url: "https://www.politico.com", source: "Politico", author: "Mark Scott" },
    { title: "Diplomatic Breakthrough: Border trade tensions eased after five-year deadlock", description: "A new joint commission has successfully negotiated the reopening of critical mountain trade routes.", urlToImage: "https://images.unsplash.com/photo-1521791136064-7986c2959d9c?w=800&q=80", url: "https://www.economist.com", source: "The Economist", author: "James Astill" },
    { title: "Urban Infrastructure Reform: Massive funding for inter-city electric rail", description: "The budget identifies sustainable mass transit as the key to economic decentralization and suburban growth.", urlToImage: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80", url: "https://www.bloomberg.com/politics", source: "Bloomberg Pol", author: "John Gittelsohn" },
    { title: "The Future of Welfare: Universal Basic Income pilot sees positive results", description: "A three-year study in a mid-sized city shows increased small business creation and lower crime rates.", urlToImage: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80", url: "https://www.nytimes.com", source: "NYT Politics", author: "Maggie Haberman" },
    { title: "Crypto Regulation: Major finance HUBS adopt unified digital asset framework", description: "A global standard for stablecoins and exchange transparency has finally been ratified by 20 leading nations.", urlToImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80", url: "https://www.ft.com/politics", source: "FT Politics", author: "Stephen Bush" },
    { title: "Higher Education Reform: Tuition-free certificates for high-demand tech jobs", description: "A new government initiative targets the reskilling of the workforce for the automation age.", urlToImage: "https://images.unsplash.com/photo-1523050335456-adeba272016f?w=800&q=80", url: "https://www.washingtonpost.com", source: "Washington Post", author: "Dan Balz" },
    { title: "Geopolitical Shift: Energy-independent nation brokers regional peace deal", description: "The rising economic power is using its surplus green energy storage to influence stable diplomacy.", urlToImage: "https://images.unsplash.com/photo-1555421689-491a97ff2040?w=800&q=80", url: "https://www.reuters.com/politics", source: "Reuters Pol", author: "Steve Holland" },
    { title: "Public Trust: Survey shows highest engagement in local municipal elections", description: "Voters are increasingly focusing on immediate community issues like zoning and water management.", urlToImage: "https://images.unsplash.com/photo-1541872703-74c5e443d1f5?w=800&q=80", url: "https://www.abcnews.com", source: "ABC News", author: "Rick Klein" }
  ],
  india: [
    { title: "Industrial Boom: Government greenlights major electronics manufacturing cluster", description: "The new SPECIAL ZONE in the southern region is expected to create over 100,000 high-tech jobs.", urlToImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80", url: "https://www.timesofindia.com", source: "TOI", author: "Aditya Raj" },
    { title: "Startup Ecosystem: Bangalore ranked among top 5 global AI innovation hubs", description: "The density of deep-tech talent and venture capital has reached a critical mass for global dominance.", urlToImage: "https://images.unsplash.com/photo-1596422846543-b5c6458405d1?w=800&q=80", url: "https://www.moneycontrol.com", source: "Moneycontrol", author: "Priya Sharma" },
    { title: "Clean Energy: World's largest solar park reaches full operational capacity", description: "The facility now powers over four million households, marking a pivotal step toward the net-zero goal.", urlToImage: "https://images.unsplash.com/photo-1509391366360-fe5bb58583bb?w=800&q=80", url: "https://www.hindustantimes.com", source: "Hindustan Times", author: "Shishir Gupta" },
    { title: "Skills Initiative: New curriculum for rural schools targets digital literacy", description: "The reach of the national fiber network is finally being matched with localized educational content.", urlToImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80", url: "https://www.ndtv.com", source: "NDTV", author: "Saurabh Gupta" },
    { title: "Mass Transit: High-speed rail corridor between major metros achieves 50% completion", description: "The project, once finished, will cut travel time by 70% and redefine interstate business hubs.", urlToImage: "https://images.unsplash.com/photo-1474487056236-0529c99a783d?w=800&q=80", url: "https://www.livemint.com", source: "Livemint", author: "Gireesh Chandra Prasad" },
    { title: "Space Milestone: Lunar rover successfully documents permanent shadow craters", description: "ISRO's latest mission has returned high-resolution data on water-ice concentrations in the south pole.", urlToImage: "https://images.unsplash.com/photo-1446776893587-63bb3298e16e?w=800&q=80", url: "https://www.thehindu.com", source: "The Hindu", author: "Madhavan Nair" },
    { title: "Fintech Revolution: Digital payment system reaches record transaction volume", description: "The interoperable framework has successfully integrated small-town vendors into the formal economy.", urlToImage: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=800&q=80", url: "https://www.business-standard.com", source: "Business Standard", author: "Nitin Sethi" },
    { title: "Agriculture Tech: Drone-based pesticide spraying adopted in several states", description: "Precision farming tools are helping farmers reduce chemical usage and improve crop yields by 20%.", urlToImage: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800&q=80", url: "https://www.indianexpress.com", source: "Indian Express", author: "Harish Damodaran" },
    { title: "Cultural Heritage: Ancient city excavation reveals sophisticated urban planning", description: "The findings suggest a level of sanitary engineering matched only by modern standards.", urlToImage: "https://images.unsplash.com/photo-1548013146-72479768bbaa?w=800&q=80", url: "https://www.timesofindia.com/culture", source: "TOI Culture", author: "Rupam Jain" },
    { title: "Medical Tourism: India becomes preferred destination for complex cardiac care", description: "High success rates and cost-effective procedures are drawing thousands from neighboring continents.", urlToImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80", url: "https://www.firstpost.com", source: "Firstpost", author: "Snehitha Rani" }
  ],
  general: [
    { title: "The Walkable City: Urban planners prioritize pedestrians over vehicles", description: "How '15-minute cities' are improving mental health and reducing the carbon footprint of major HUBS.", urlToImage: "https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?w=800&q=80", url: "https://www.theatlantic.com", source: "The Atlantic", author: "Ed Yong" },
    { title: "Remote Work Longevity: Companies commit to permanent distributed model", description: "Data shows that flexibility is now the number one factor for talent retention in the contemporary market.", urlToImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80", url: "https://www.nyt.com", source: "NYT", author: "Ezra Klein" },
    { title: "Global Literacy: Philanthropic coalition targets universal reading access", description: "A multi-billion dollar fund has been established to provide digital tablets to every child in developing regions.", urlToImage: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80", url: "https://www.forbes.com", source: "Forbes", author: "Kerry Dolan" },
    { title: "AI Ethics: Global council proposes common standards for responsible tech", description: "The guidelines focus on transparent algorithms and reducing systemic bias in automated decisions.", urlToImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80", url: "https://www.technologyreview.com", source: "MIT Tech Review", author: "Karen Hao" },
    { title: "Circular Economy: Manufacturing shifts from 'Take-Make-Waste' model", description: "How closed-loop production is transforming industries and saving billions in raw material costs.", urlToImage: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80", url: "https://www.weforum.org", source: "WEF News", author: "Kate Whiting" },
    { title: "Ocean Cleanup: Massive trash-collecting network begins mid-pacific operation", description: "A high-tech floating barrier system aims to remove 50% of the Great Pacific Garbage Patch in five years.", urlToImage: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80", url: "https://www.theverge.com/ocean", source: "The Verge", author: "Elizabeth Lopatto" },
    { title: "The Return of the Library: Community centers thrive in the digital age", description: "Beyond books, public libraries are becoming essential HUBS for tool sharing and high-speed working spaces.", urlToImage: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80", url: "https://www.smithsonianmag.com", source: "Smithsonian", author: "Theresa Machemer" },
    { title: "Modern Nomads: The resurgence of high-tech communal living", description: "Shared residential spaces are offering a balance of privacy and shared resources for the remote era.", urlToImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80", url: "https://www.curbed.com", source: "Curbed", author: "Verity Brown" },
    { title: "The Longevity Gap: How lifestyle factors influence urban life expectancy", description: "New research highlights the critical impact of green space access and communal social structures.", urlToImage: "https://images.unsplash.com/photo-1529333166437-08c3507df044?w=800&q=80", url: "https://www.vox.com", source: "Vox", author: "Umair Irfan" },
    { title: "Community Solar: Rooftop sharing networks provide affordable green power", description: "New localized grids allow neighbors to trade excess solar energy without relying on major utility hubs.", urlToImage: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80", url: "https://www.qz.com", source: "Quartz", author: "Tim McDonnell" }
  ]
};